project:
  type: website

website:
  title: "R4DSA meetup"
  navbar:
    left:
      - text: Nov-Dev 2022
        menu: 
          - text: Randomisation Inference Statistics
            href: nov2022/TidyModels1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

